const blogs = [
    {
      id: 1,
      title: "Understanding JavaScript Closures",
      author: "John Doe",
      content: "Closures are an important concept in JavaScript that allow functions to retain access to variables from their outer scope...",
      tags: ["JavaScript", "Closures", "Functions"],
      publishedDate: "2024-02-13",
      views: 1024,
      likes: 230,
    },
    {
      id: 2,
      title: "Mastering Asynchronous JavaScript",
      author: "Jane Smith",
      content: "Asynchronous programming is crucial for web development. JavaScript provides various methods such as Promises and Async/Await...",
      tags: ["JavaScript", "Async", "Promises"],
      publishedDate: "2024-02-10",
      views: 876,
      likes: 190,
    },
    {
      id: 3,
      title: "A Guide to JavaScript ES6 Features",
      author: "Alice Johnson",
      content: "ES6 introduced several new features such as arrow functions, template literals, and destructuring, making JavaScript more powerful...",
      tags: ["JavaScript", "ES6", "ModernJS"],
      publishedDate: "2024-01-25",
      views: 1432,
      likes: 310,
    },
    {
      id: 4,
      title: "JavaScript vs TypeScript: Which One Should You Choose?",
      author: "Bob Williams",
      content: "Both JavaScript and TypeScript are widely used in web development, but they have key differences that can impact your project...",
      tags: ["JavaScript", "TypeScript", "Comparison"],
      publishedDate: "2024-02-05",
      views: 1234,
      likes: 275,
    },
    {
      id: 5,
      title: "How to Optimize JavaScript Performance",
      author: "Charlie Brown",
      content: "Optimizing JavaScript code can enhance web performance significantly. Techniques like code splitting, lazy loading, and caching...",
      tags: ["JavaScript", "Performance", "Optimization"],
      publishedDate: "2024-01-30",
      views: 987,
      likes: 210,
    },
  ];

  export default blogs;